### PR TITLE
Container -> ScreenHandler

### LINKED ISSUE #61: Container -> ScreenHandler
**Names of the classes**
container becomes screenhandler

**Additional Context**
yarn parity

### PR DESCRIPTION
**Pull request by BoogieMonster1O1**
Closes #61 

```groovy
 Changes to be committed:
	modified:   mappings/net/minecraft/block/AnvilBlock.mapping
	modified:   mappings/net/minecraft/block/BigMushroomBlock.mapping
	modified:   mappings/net/minecraft/block/CraftingTableBlock.mapping
	modified:   mappings/net/minecraft/block/DirtBlock.mapping
	modified:   mappings/net/minecraft/block/DoublePlantBlock.mapping
	modified:   mappings/net/minecraft/block/InfestedBlock.maping
	modified:   mappings/net/minecraft/block/LeverBlock.mapping
	modified:   mappings/net/minecraft/block/PlanksBlock.mapping
	modified:   mappings/net/minecraft/block/PrismarineBlock.mapping
	modified:   mappings/net/minecraft/block/QuartzBlock.mapping
	modified:   mappings/net/minecraft/block/RedSandstoneBlock.mapping
	modified:   mappings/net/minecraft/block/RedSandstoneSlabBlock.mapping
	modified:   mappings/net/minecraft/block/SandBlock.mapping
	modified:   mappings/net/minecraft/block/SandstoneBlock.mapping
	modified:   mappings/net/minecraft/block/StoneBlock.mapping
	modified:   mappings/net/minecraft/block/StoneSlabBlock.mapping
	modified:   mappings/net/minecraft/block/TallPlantBlock.mapping
	modified:   mappings/net/minecraft/block/dispenser/ItemDispenserBehavior.mapping
	new file:   mappings/net/minecraft/block/entity/HopperProvider.mapping
	modified:   mappings/net/minecraft/client/color/world/FoliageColors.mapping
	modified:   mappings/net/minecraft/client/color/world/GrassColors.mapping
	modified:   mappings/net/minecraft/client/gl/ShaderParseException.mapping
	modified:   mappings/net/minecraft/client/gui/hud/spectator/SpectatorMenuCommand.mapping
	modified:   mappings/net/minecraft/client/gui/screen/DeathScreen.mapping
	modified:   mappings/net/minecraft/client/gui/screen/ProgressScreen.mapping
	modified:   mappings/net/minecraft/client/gui/screen/ingame/AnvilScreen.mapping
	modified:   mappings/net/minecraft/client/gui/screen/ingame/CreativeInventoryScreen.mapping
	new file:   mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
	modified:   mappings/net/minecraft/client/main/Main.mapping
	modified:   mappings/net/minecraft/client/particle/ExplosionEmitterParticle.mapping
	modified:   mappings/net/minecraft/client/particle/ParticleType.mapping
	modified:   mappings/net/minecraft/client/render/GameRenderer.mapping
	modified:   mappings/net/minecraft/client/render/chunk/ChunkOcclusionData.mapping
	modified:   mappings/net/minecraft/client/render/chunk/ChunkOcclusionDataBuilder.mapping
	modified:   mappings/net/minecraft/client/render/entity/PlayerModelPart.mapping
	modified:   mappings/net/minecraft/client/render/entity/model/EndermanEntityModel.mapping
	modified:   mappings/net/minecraft/client/render/model/WeightedBakedModel.mapping
	modified:   mappings/net/minecraft/client/render/model/json/ModelElementTexture.mapping
	modified:   mappings/net/minecraft/client/resource/language/LanguageDefinition.mapping
	modified:   mappings/net/minecraft/client/resource/metadata/AnimationFrameResourceMetadata.mapping
	modified:   mappings/net/minecraft/client/sound/SoundCategory.mapping
	modified:   mappings/net/minecraft/client/sound/SoundContainer.mapping
	modified:   mappings/net/minecraft/client/sound/SoundManager.mapping
	modified:   mappings/net/minecraft/client/sound/SoundSystem.mapping
	modified:   mappings/net/minecraft/client/util/ModelIdentifier.mapping
	modified:   mappings/net/minecraft/client/world/ClientWorld.mapping
	modified:   mappings/net/minecraft/enchantment/ThornsEnchantment.mapping
	modified:   mappings/net/minecraft/entity/FireworkEntity.mapping
	modified:   mappings/net/minecraft/entity/ai/goal/Goal.mapping
	modified:   mappings/net/minecraft/entity/ai/goal/WanderAroundGoal.mapping
	modified:   mappings/net/minecraft/entity/attribute/AbstractEntityAttributeContainer.mapping
	modified:   mappings/net/minecraft/entity/attribute/EntityAttribute.mapping
	modified:   mappings/net/minecraft/entity/attribute/EntityAttributeContainer.mapping
	modified:   mappings/net/minecraft/entity/decoration/PaintingEntity.mapping
	modified:   mappings/net/minecraft/entity/mob/CreeperEntity.mapping
	modified:   mappings/net/minecraft/entity/passive/IronGolemEntity.mapping
	modified:   mappings/net/minecraft/entity/passive/SheepEntity.mapping
	modified:   mappings/net/minecraft/entity/player/PlayerAbilities.mapping
	modified:   mappings/net/minecraft/entity/player/PlayerEntity.mapping
	modified:   mappings/net/minecraft/entity/vehicle/AbstractMinecartEntity.mapping
	modified:   mappings/net/minecraft/entity/vehicle/FurnaceMinecartEntity.mapping
	modified:   mappings/net/minecraft/entity/vehicle/HopperMinecartEntity.mapping
	modified:   mappings/net/minecraft/entity/vehicle/TntMinecartEntity.mapping
	new file:   mappings/net/minecraft/inventory/InventoryLock.mapping
	modified:   mappings/net/minecraft/inventory/SidedInventory.mapping
	modified:   mappings/net/minecraft/item/FishItem.mapping
	modified:   mappings/net/minecraft/nbt/CompoundTag.mapping
	modified:   mappings/net/minecraft/nbt/NbtIo.mapping
	modified:   mappings/net/minecraft/network/NetworkEncryptionUtils.mapping
	modified:   mappings/net/minecraft/network/NetworkState.mapping
	modified:   mappings/net/minecraft/network/Packet.mapping
	modified:   mappings/net/minecraft/network/PacketDeflater.mapping
	modified:   mappings/net/minecraft/network/ServerAddress.mapping
	modified:   mappings/net/minecraft/network/encryption/PacketEncryptionManager.mapping
	modified:   mappings/net/minecraft/network/listener/ClientLoginPacketListener.mapping
	modified:   mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
	modified:   mappings/net/minecraft/network/packet/c2s/play/ButtonClickC2SPacket.mapping
	modified:   mappings/net/minecraft/network/packet/c2s/play/ConfirmGuiActionC2SPacket.mapping
	modified:   mappings/net/minecraft/network/packet/c2s/play/PlayerInputC2SPacket.mapping
	modified:   mappings/net/minecraft/network/packet/c2s/play/UpdatePlayerAbilitiesC2SPacket.mapping
	modified:   mappings/net/minecraft/network/packet/s2c/login/LoginHelloS2CPacket.mapping
	new file:   mappings/net/minecraft/network/packet/s2c/play/CloseScreenHandlerS2CPacket.mapping
	modified:   mappings/net/minecraft/network/packet/s2c/play/ConfirmGuiActionS2CPacket.mapping
	modified:   mappings/net/minecraft/network/packet/s2c/play/EntityAnimationS2CPacket.mapping
	modified:   mappings/net/minecraft/network/packet/s2c/play/EntityPositionS2CPacket.mapping
	modified:   mappings/net/minecraft/network/packet/s2c/play/EntitySetHeadYawS2CPacket.mapping
	modified:   mappings/net/minecraft/network/packet/s2c/play/EntityStatusEffectS2CPacket.mapping
	modified:   mappings/net/minecraft/network/packet/s2c/play/EntityStatusS2CPacket.mapping
	modified:   mappings/net/minecraft/network/packet/s2c/play/PlayerAbilitiesS2CPacket.mapping
	new file:   mappings/net/minecraft/network/packet/s2c/play/ScreenHandlerPropertyUpdateS2CPacket.mapping
	new file:   mappings/net/minecraft/network/packet/s2c/play/ScreenHandlerSlotUpdateS2CPacket.mapping
	new file:   mappings/net/minecraft/recipe/RecipeProvider.mapping
	new file:   mappings/net/minecraft/recipe/RecipeRegistry.mapping
	modified:   mappings/net/minecraft/scoreboard/ScoreboardCriterion.mapping
	new file:   mappings/net/minecraft/screen/AnvilScreenHandler.mapping
	new file:   mappings/net/minecraft/screen/BeaconScreenHandler.mapping
	new file:   mappings/net/minecraft/screen/BrewingStandScreenHandler.mapping
	new file:   mappings/net/minecraft/screen/ChestScreenHandler.mapping
	new file:   mappings/net/minecraft/screen/CraftingResultSlot.mapping
	new file:   mappings/net/minecraft/screen/CraftingTableScreenHandler.mapping
	new file:   mappings/net/minecraft/screen/EnchantingTableScreenHandler.mapping
	new file:   mappings/net/minecraft/screen/FurnaceFuelSlot.mapping
	new file:   mappings/net/minecraft/screen/FurnaceOutputSlot.mapping
	new file:   mappings/net/minecraft/screen/FurnaceScreenHandler.mapping
	new file:   mappings/net/minecraft/screen/Generic3x3ScreenHandler.mapping
	new file:   mappings/net/minecraft/screen/HopperScreenHandler.mapping
	new file:   mappings/net/minecraft/screen/HorseScreenHandler.mapping
	new file:   mappings/net/minecraft/screen/MerchantScreenHandler.mapping
	new file:   mappings/net/minecraft/screen/PlayerScreenHandler.mapping
	new file:   mappings/net/minecraft/screen/ScreenHandler.mapping
	new file:   mappings/net/minecraft/screen/ScreenHandlerListener.mapping
	new file:   mappings/net/minecraft/screen/ScreenHandlerProvider.mapping
	new file:   mappings/net/minecraft/screen/Slot.mapping
	new file:   mappings/net/minecraft/screen/TradeOutputSlot.mapping
	modified:   mappings/net/minecraft/server/BannedIpList.mapping
	modified:   mappings/net/minecraft/server/MinecraftServer.mapping
	modified:   mappings/net/minecraft/server/dedicated/DedicatedServer.mapping
	modified:   mappings/net/minecraft/server/dedicated/gui/PlayerListGui.mapping
	modified:   mappings/net/minecraft/server/dedicated/gui/PlayerStatsGui.mapping
	modified:   mappings/net/minecraft/server/network/DemoServerPlayerInteractionManager.mapping
	modified:   mappings/net/minecraft/server/rcon/BufferHelper.mapping
	modified:   mappings/net/minecraft/server/rcon/DataStreamHelper.mapping
	modified:   mappings/net/minecraft/server/rcon/RconClient.mapping
	modified:   mappings/net/minecraft/server/rcon/RconServer.mapping
	modified:   mappings/net/minecraft/state/property/Property.mapping
	modified:   mappings/net/minecraft/text/ClickEvent.mapping
	modified:   mappings/net/minecraft/text/HoverEvent.mapping
	modified:   mappings/net/minecraft/text/ScoreText.mapping
	modified:   mappings/net/minecraft/util/DyeColor.mapping
	modified:   mappings/net/minecraft/util/Formatting.mapping
	modified:   mappings/net/minecraft/util/JsonElementProvider.mapping
	modified:   mappings/net/minecraft/util/JsonHelper.mapping
	modified:   mappings/net/minecraft/util/JsonSet.mapping
	modified:   mappings/net/minecraft/util/MetricsData.mapping
	modified:   mappings/net/minecraft/util/Pair.mapping
	modified:   mappings/net/minecraft/util/PrintStreamLogger.mapping
	modified:   mappings/net/minecraft/util/TypeFilterableList.mapping
	modified:   mappings/net/minecraft/util/crash/CrashException.mapping
	modified:   mappings/net/minecraft/util/math/Direction.mapping
	modified:   mappings/net/minecraft/util/math/Position.mapping
	modified:   mappings/net/minecraft/util/math/PositionImpl.mapping
	modified:   mappings/net/minecraft/util/math/Vec3d.mapping
	modified:   mappings/net/minecraft/util/profiler/Profiler.mapping
	modified:   mappings/net/minecraft/village/TraderOfferList.mapping
	modified:   mappings/net/minecraft/world/Difficulty.mapping
	modified:   mappings/net/minecraft/world/level/LevelInfo.mapping
	modified:   mappings/net/minecraft/world/level/LevelProperties.mapping
	modified:   mappings/net/minecraft/world/level/storage/AlphaChunkDataArray.mapping
	new file:   net/minecraft/client/gui/screen/ingame/CreativeInventoryScreen.mapping
	new file:   net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
	new file:   net/minecraft/entity/player/PlayerEntity.mapping
	new file:   net/minecraft/recipe/RecipeProvider.mapping
	new file:   net/minecraft/recipe/RecipeRegistry.mapping
	new file:   net/minecraft/screen/AnvilScreenHandler.mapping
	new file:   net/minecraft/screen/BeaconContainer.mapping
	new file:   net/minecraft/screen/BrewingStandScreenHandler.mapping
	new file:   net/minecraft/screen/ChestScreenHandler.mapping
	new file:   net/minecraft/screen/CraftingResultSlot.mapping
	new file:   net/minecraft/screen/CraftingTableScreenHandler.mapping
	new file:   net/minecraft/screen/EnchantingTableScreenHandler.mapping
	new file:   net/minecraft/screen/FurnaceFuelSlot.mapping
	new file:   net/minecraft/screen/FurnaceOutputSlot.mapping
	new file:   net/minecraft/screen/FurnaceScreenHandler.mapping
	new file:   net/minecraft/screen/Generic3x3ScreenHandler.mapping
	new file:   net/minecraft/screen/HopperScreenHandler.mapping
	new file:   net/minecraft/screen/HorseScreenHandler.mapping
	new file:   net/minecraft/screen/MerchantScreenHandler.mapping
	new file:   net/minecraft/screen/PlayerScreenHandler.mapping
	new file:   net/minecraft/screen/ScreenHandler.mapping
	new file:   net/minecraft/screen/ScreenHandlerListener.mapping
	new file:   net/minecraft/screen/Slot.mapping
	new file:   net/minecraft/screen/TradeOutputSlot.mapping
```
Most of these files were not modified. Enigma just decided to rearrange methods and parameters.

### CODE REVIEW

**Comment by shedaniel** [comment]
no, it's either Container or ScreenHandler (the full name)

**Comment by hYdos** [comment]
no, look at the current yarn names. you will find stuff shortened to handler everywhere.

**Comment by shedaniel** [comment]
yarn bad yes let's keep container

**Comment by BoogieMonster1O1** [comment]
i don't want to rewrite surely enough items to match these conventions
kthxbye

**Comment by hYdos** [comment]
wait... thats illegal

**Pull request closed without merging**
