### PR TITLE
Most missing methods and parameters, and javadoc for the Block class

### PR DESCRIPTION
**Pull request by BoogieMonster1O1**
Every first mod starts with a block. Well, that's true for me. Blocks are a simple and easy component to implement into the game, so they should be given high priority and be well documented. This was probably the craziest and hardest Javadoc I had to write so I hope it's worth it.

*Again, please don't squash merge*

Changelog:-
```scala
 Changes to be committed:
	modified:   mappings/net/minecraft/block/Block.mapping
	modified:   mappings/net/minecraft/block/BlockState.mapping
	modified:   mappings/net/minecraft/block/Material.mapping
	modified:   mappings/net/minecraft/stat/Stats.mapping
	modified:   mappings/net/minecraft/block/Block.mapping
	modified:   mappings/net/minecraft/util/registry/DefaultedRegistry.mapping
	modified:   mappings/net/minecraft/block/Block.mapping
	modified:   mappings/net/minecraft/block/BlockState.mapping
	modified:   mappings/net/minecraft/block/Material.mapping
	modified:   mappings/net/minecraft/block/Block.mapping
	modified:   mappings/net/minecraft/block/Block.mapping
	modified:   mappings/net/minecraft/block/Block.mapping
	modified:   mappings/net/minecraft/block/Block.mapping
```

### CODE REVIEW

**Comment by shedaniel** [comment]
Squash merge makes the history clean :irritatered:

**Comment by BoogieMonster1O1** [comment]
> Squash merge makes the history clean :irritatered:

squash merges make contributing again a heck of a task

**Comment by shedaniel** [comment]
Do you just don't know how to use git? I will again merge this to make your life better.

**Comment by BoogieMonster1O1** [comment]
> Do you just don't know how to use git? I will again merge this to make your life better.

I do, it's just that branching, switching, fetching, merging, pushing and then starting is a bit more tedious than just continue collaborating

**Pull request merged**
