### PR TITLE
improve PlayerSkinProvider inner classes's packages

### PR DESCRIPTION
**Pull request by HowardZHY**

### CODE REVIEW

**Comment by HowardZHY** [comment]
anything else needs to change?

**Comment by arthurbambou** [comment]
Still failing to build

**Comment by HowardZHY** [comment]
> Still failing to build

There's still sth wrong with LF maven.

**Comment by BleachDev** [comment]
the build succeeded

**Comment by HowardZHY** [comment]
Then merge and update 1.7-1.7.9 yarn

**Pull request merged**
