### PR TITLE
Mappings and Javadoc for GlStateManager

### LINKED ISSUE #42: Write javadocs for the complicated GlStateManager class

### LINKED ISSUE #43: Javadoc fails to generate
Log:
```make

> Task :downloadVersionsManifest
:downloading minecraft versions manifest

> Task :downloadMcLibs
:downloading minecraft libraries

> Task :downloadIntermediary
Download https://github.com/Legacy-Fabric/Legacy-Intermediaries/raw/master/mappings/1.8.9.tiny

> Task :downloadMcJars
:downloading minecraft jars

> Task :mergeJars
:merging jars

> Task :mapIntermediaryJar
:mapping minecraft to intermediary

> Task :buildYarnTiny
:generating tiny mappings

> Task :invertIntermediary
:building inverted intermediary
Loading mapping file...
Rewriting mappings...
Done!

> Task :mergeTiny
:merging yarn and intermediary
Reading 1.8.9-intermediary-inverted.tiny
Reading yarn-mappings.tiny
Processing...
Done!
:reordering merged intermediary
Loading mapping file...
Rewriting mappings...
Done!

> Task :buildTinyWithEnum
:seeking auto-mappable fields
Found 1045 interesting names.

> Task :mapNamedJar
:mapping minecraft to named

> Task :genFakeSource FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Volumes/FILES/curst/build.gradle' line: 690

* What went wrong:
Execution failed for task ':genFakeSource'.
> not a valid name: true

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 42s
13 actionable tasks: 13 executed

```

### PR DESCRIPTION
**Pull request by BoogieMonster1O1**
Mapped all(lots if not all) methods and fields in GlStateManager, and wrote Javadoc for them. Also fixes a critical bug (*which I might have introduced*).

Closes #42 
Closes #43

### CODE REVIEW

**Comment by BoogieMonster1O1** [comment]
Javadoc doesn't seem to get generated, I'll see what's going on

**Comment by BoogieMonster1O1** [comment]
Fixed the javadoc bug, it is ready for merge

**Comment by TheMadHau5** [comment]
squash merge?

**Comment by BoogieMonster1O1** [comment]
> squash merge?
NO, I don't want to re fork yarn or do some branch shenanigans every single time I want to contribute

**Comment by shedaniel** [comment]
_I think you just don't know how to use git, you don't need to refork, but I will just merge to make your life easier_

**Pull request merged**
