### PR TITLE
Some 1.8.9 mappings

### PR DESCRIPTION
**Pull request by jaydevelopsshit**
A small contribution to the 1.8.9 mappings.

(Not the same as the pr I submitted earlier)

### CODE REVIEW

**Review by arthurbambou — APPROVED** [review]

**Comment by jaydevelopsshit** [comment]
What the heck? Am I banned from the discord?

**Comment by PseudoDistant** [comment]
> Why am I banned from the discord?

Relatabl
gabCoolSunglasses
e

**Comment by hYdos** [comment]
yate

**Comment by jaydevelopsshit** [comment]
bruh... yall aren't even gonna tell my why?

**Comment by hYdos** [comment]
> bruh... yall aren't even gonna tell my why?

GDude had already explained it before you where banned.

**Comment by jaydevelopsshit** [comment]
Explained what, I was afk while I got banned

Lemme guess, politics?

**Comment by arthurbambou** [comment]
> > Why am I banned from the discord?
> 
> 
> 
> Relatable
> 
> gabCoolSunglasses

Why? You never got banned from the server, you left on your own??

**Comment by jaydevelopsshit** [comment]
> > > Why am I banned from the discord?
> > 
> > 
> > Relatable
> > gabCoolSunglasses
> 
> Why? You never got banned from the server, you left on your own?? (Replying to Distant)

Can you at least give me a reason, I want to contribute to this.

**Comment by hYdos** [comment]
> > > > Why am I banned from the discord?
> > > 
> > > 
> > > Relatable
> > > gabCoolSunglasses
> > 
> > 
> > Why? You never got banned from the server, you left on your own?? (Replying to Distant)
> 
> Can you at least give me a reason, I want to contribute to this project.

https://cdn.discordapp.com/attachments/679635651666378753/921168105542144050/Screenshot_20211216-223235.jpg

**Comment by jaydevelopsshit** [comment]
> > > > > Why am I banned from the discord?
> > > > 
> > > > 
> > > > Relatable
> > > > gabCoolSunglasses
> > > 
> > > 
> > > Why? You never got banned from the server, you left on your own?? (Replying to Distant)
> > 
> > 
> > Can you at least give me a reason, I want to contribute to this project.
> 
> https://cdn.discordapp.com/attachments/679635651666378753/921168105542144050/Screenshot_20211216-223235.jpg

Seriously? Why every mc project out there gotta be so damn political.

**Comment by jaydevelopsshit** [comment]
That was in april...

**Comment by jaydevelopsshit** [comment]
alright, fuck this i guess

**Comment by PseudoDistant** [comment]
> > > Why am I banned from the discord?
> > 
> > 
> > Relatable
> > gabCoolSunglasses
> 
> Why? You never got banned from the server, you left on your own?? (Replying to Distant)

I know. :>
I just say relatable to random stuff.

**Comment by jaydevelopsshit** [comment]
Closing cuz of all the comment junk

**Comment by jaydevelopsshit** [comment]
:)

**Review by arthurbambou — APPROVED** [review]

**Pull request merged**
